name: my_flutter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  cupertino_icons: ^1.0.8
  fluentui_system_icons: ^1.1.195
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/flight_nyc_london.jpeg
  - assets/images/flight_dhaka_shanghai.jpeg
  - assets/images/flight_tokyo_seoul.jpeg
  - assets/images/hotel1.jpeg
  - assets/images/hotel2.jpeg
  - assets/images/hotel4.jpeg
  - assets/images/ibrahim.jpeg